name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        node-version: ['20']

    runs-on: ${{ matrix.platform }}

    steps:
    # Avoid issues with Prettier on Windows
    - name: Disable git automatic line ending conversion
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
